### PR TITLE
Update .pre-commit-config.yaml

### PR DESCRIPTION
**Pull request by mosfet80**
update pre-commit-hooks and codespell to last version

### CODE REVIEW

**Comment by mosfet80** [comment]
fixed: .devcontainer/Dockerfile:80: isntall ==> install, isn't all

**Comment by ChrisThrasher** [comment]
> fixed: .devcontainer/Dockerfile:80: isntall ==> install, isn't all

Can you commit that spelling fix please?

**Comment by ChrisThrasher** [comment]
Any particular reason you want to upgrade these two dependencies?

**Review by tylerjw — APPROVED** [review]
I don't see any harm in bumbing the versions of these tools, they pass ci, approving.

**Pull request merged**
