### PR TITLE
Implement `rsl::rng()` with `std::optional`

### PR DESCRIPTION
**Pull request by ChrisThrasher**
I think this is a more expressive and readable alternative to the status quo. That `first` variable was never all that intuitive to me.

### CODE REVIEW

**Review by tylerjw — DISMISSED** [review]
This is easier to read.

**Comment by ChrisThrasher** [comment]
Waiting on #69 which will hopefully address the code coverage job failing.

**Review by tylerjw — APPROVED** [review]

**Comment by ChrisThrasher** [comment]
I want to merge this but code coverage will keep failing in future PRs so we have to do something about it.

**Comment by ChrisThrasher** [comment]
Those coverage jobs are still bothering us. Even if we disable them to merge this PR, they'll incumber future PRs. Can we just disable them or tweak them to stop being so sensitive until we figure out why coverage is reporting <100%? I really want this bug fix to make it into the next release so this PR can be stalled much longer.

**Review by tylerjw — APPROVED** [review]

**Pull request merged**
